# The URL the site will be built for
base_url = "https://tilde.team/~birabittoh/"
title = "BiRabittoh"
description = "test"
default_language = "en"
minify_html = true
generate_feed = true
compile_sass = false
build_search_index = false
taxonomies = [
  { name = "tags" },
]
theme = "anemone"

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = true
#highlight_theme = "gruvbox-dark"

[extra]
author = "Marco Andronaco"
header_nav = [
  { name = "/home/", url = "/" },
  { name = "/about/", url = "/about" },
  { name = "/journal/", url = "/journal" },
  { name = "/blog/", url = "/blog" },
]
