# The URL the site will be built for
base_url = "https://tilde.team/~birabittoh/"
description = "Tech and privacy ramblings from a random italian dude."
title = "BiRabittoh"
author = "BiRabittoh"
default_language = "en"
minify_html = true
generate_feed = true
compile_sass = false
build_search_index = false
taxonomies = [
  { name = "tags", feed = true },
]
theme = "anemone"

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = false
#highlight_theme = "gruvbox-dark"

[extra]
header_nav = [
  { name = "/home/", url = "/" },
  { name = "/about/", url = "/about" },
  { name = "/journal/", url = "/journal" },
  { name = "/blog/", url = "/blog" },
]
default_theme = "dark" # default: 'light'
