name: GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: checkout  
        uses: actions/checkout@v3
        with:
          submodules: true  # Fetch theme via git submodule
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
